version: "3.8"

services:
  stackoverflow_app:
    platform: linux/x86_64
    image: mysql:8.0.28
    restart: always
    ports:
      - "3331:3306"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - overflow_app_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  overflow_app_data:
    driver: local
